################################################################################
# run_analysis.R
# Main script to run the complete IMD vaccination cost-effectiveness analysis
#
# WORKFLOW OVERVIEW:
# ==================
# This script is designed to work in conjunction with run_psa_distributions_only.R
# for efficient PSA parameter validation and model execution.
#
# RECOMMENDED WORKFLOW:
# ---------------------
# STEP 1: Generate and validate PSA parameter distributions (OPTIONAL BUT RECOMMENDED)
#         Run: source("run_psa_distributions_only.R")
#         - Generates PSA parameter samples (saved to psa_samples.rds)
#         - Creates distribution plots for visual validation
#         - Fast execution (seconds) - no model simulation
#         - Validates that parameter distributions are correctly specified
#
# STEP 2: Run complete cost-effectiveness analysis
#         Run: source("run_analysis.R")
#         - Automatically detects and reuses existing PSA samples (if available)
#         - Runs deterministic analysis
#         - Runs probabilistic sensitivity analysis (PSA)
#         - Runs one-way sensitivity analysis (OWSA)
#         - Generates all cost-effectiveness outputs (ICER, CEAC, EVPI, etc.)
#
# PSA SAMPLE REUSE LOGIC:
# -----------------------
# - If REUSE_PSA_SAMPLES = TRUE and psa_samples.rds exists:
#   → Loads existing PSA parameter samples (saves time, ensures consistency)
#   → Validates that number of samples matches N_SIMULATIONS
#   → Falls back to generating new samples if validation fails
#
# - If REUSE_PSA_SAMPLES = FALSE or psa_samples.rds doesn't exist:
#   → Generates new PSA parameter samples
#   → Saves them to psa_samples.rds for future use
#
# KEY CONFIGURATION PARAMETERS:
# ------------------------------
# - COHORT_SIZE: Number of individuals in the cohort
# - N_SIMULATIONS: Number of PSA iterations (use ≥1000 for final analysis)
# - ANALYSIS_PERSPECTIVE: "healthcare", "societal", or "both"
# - REUSE_PSA_SAMPLES: TRUE to reuse existing samples, FALSE to regenerate
# - WTP_THRESHOLD: Willingness-to-pay threshold for cost-effectiveness
# - CREATE_OWSA_PLOTS: TRUE to generate tornado diagrams
#
# OUTPUTS:
# --------
# Tables (outputs/tables/):
#   - deterministic_results_[perspective].csv
#   - deterministic_icers_[perspective].csv
#   - psa_long_results_[perspective].csv
#   - owsa_output_cost_[perspective].csv
#   - owsa_output_qalys_[perspective].csv
#
# Figures (outputs/figures/):
#   - deterministic_icers_frontier_[perspective].png
#   - psa_ceac_[perspective].png (cost-effectiveness acceptability curve)
#   - psa_evpi_[perspective].png (expected value of perfect information)
#   - owsa_tornado_*.png (one-way sensitivity tornado diagrams)
#
# NOTE: PSA distribution plots are NOT generated by this script.
#       Use run_psa_distributions_only.R for parameter distribution visualization.
#
################################################################################

# ============================================================
# START TIMER
# ============================================================
start_time <- Sys.time()
# ============================================================
# PACKAGE INSTALLATION AND LOADING
# ============================================================

# Install pacman if needed
if (!require("pacman", quietly = TRUE)) {
  install.packages("pacman", repos = "https://cloud.r-project.org")
}

# Load packages
library(pacman)
p_load(here, readxl, ggplot2, dplyr, tidyr, purrr, stringr,
       tibble, doParallel, foreach, parallel, diagram, reshape2, readr)
p_load_gh("DARTH-git/darthtools")
p_load(dampack)


# ============================================================
# SOURCE ALL MODEL FILES
# ============================================================

message("[INFO] Sourcing model files...")

# Source numbered R files in order
files <- list.files("R", pattern = "^[0-9]{2}.*\\.R$", full.names = TRUE)
files <- files[order(files)]

for (file in files) {
  message(paste("  Loading:", basename(file)))
  source(file)
}

message("[INFO] All model files loaded successfully\n")
# ============================================================
# CONFIGURATION SECTION - EDIT THESE VALUES
# ============================================================

# Analysis settings
#N_SIMULATIONS <-2500L       # Number of PSA simulations
COHORT_SIZE <- n_cohort       # Number of individuals in the cohort -  defined in 02_globals.R

WTP_THRESHOLD <- 50000      # Willingness-to-pay threshold (CAD per QALY)
# ANALYSIS_PERSPECTIVE <- "both"  # "healthcare", "societal", or "both"

# PSA options
REUSE_PSA_SAMPLES <- TRUE   # Set to TRUE to reuse existing PSA samples (if available)
# Set to FALSE to generate new PSA samples

# OWSA Configuration - EDIT HERE
owsa_comparators <- c("all")  # Options: "MenC", "MenACWY", c("MenC", "MenACWY"), "all"
owsa_strategies <- NULL  # NULL = all except comparators, or specify: c("MenACWY", "MenABCWY")

# Visualization options
CREATE_OWSA_PLOTS <- TRUE   # Set to FALSE to skip OWSA tornado plots

# SET seed for reproducibility
RANDOM_SEED <- 2025

# ============================================================
# VALIDATE AND SET PERSPECTIVES
# ============================================================

# Validate perspective input
if (!ANALYSIS_PERSPECTIVE %in% c("healthcare", "societal", "both")) {
  stop("ANALYSIS_PERSPECTIVE must be 'healthcare', 'societal', or 'both'")
}

# Determine which perspectives to run
if (ANALYSIS_PERSPECTIVE == "both") {
  perspectives_to_run <- c("healthcare", "societal")
} else {
  perspectives_to_run <- ANALYSIS_PERSPECTIVE
}

message("\n========================================")
message("IMD VACCINATION ANALYSIS - CONFIGURATION")
message("========================================")
message(paste("Cohort Size:", COHORT_SIZE))
message(paste("PSA Simulations:", N_SIMULATIONS))
message(paste("WTP Threshold: CAD", format(WTP_THRESHOLD, big.mark = ",")))
message(paste("Perspective(s):", paste(perspectives_to_run, collapse = " & ")))
message(paste("Random Seed:", RANDOM_SEED))
message(paste("Reuse PSA Samples:", ifelse(REUSE_PSA_SAMPLES, "YES (if available)", "NO (generate new)")))
message(paste("OWSA Plots:", ifelse(CREATE_OWSA_PLOTS, "YES", "NO")))
message("========================================\n")

# Set random seed
set.seed(RANDOM_SEED)


# ============================================================
# LOAD OR GENERATE PSA SAMPLES (PERSPECTIVE-INDEPENDENT)
# ============================================================

message("\n========================================")
message("PSA PARAMETER SAMPLES")
message("========================================\n")

# Set temporary perspective for parameter loading
perspective <- "healthcare"
n_cohort <- as.integer(COHORT_SIZE)

# Load base parameters
params_bc <- get_base_params()

# Path to saved PSA samples
psa_samples_file <- file.path(OUT_TAB, "psa_samples.rds")

# Try to load existing PSA samples if requested
psa_loaded <- FALSE
if (REUSE_PSA_SAMPLES && file.exists(psa_samples_file)) {
  
  message("[INFO] Found existing PSA samples file")
  message("[INFO] Attempting to load PSA samples from:", psa_samples_file)
  
  tryCatch({
    psa_samples_output <- readRDS(psa_samples_file)
    
    # Validate loaded samples
    if (!is.null(psa_samples_output$samples) && 
        !is.null(psa_samples_output$psa_df)) {
      
      n_samples_loaded <- length(psa_samples_output$samples)
      
      # Check if number of samples matches
      if (n_samples_loaded == N_SIMULATIONS) {
        message("[INFO] ✓ Successfully loaded PSA samples (n = ", n_samples_loaded, ")")
        psa_parameter_samples <- psa_samples_output$samples
        psa_parameter_df <- psa_samples_output$psa_df
        psa_loaded <- TRUE
      } else {
        message("[WARN] PSA samples file has ", n_samples_loaded, " samples, but N_SIMULATIONS = ", N_SIMULATIONS)
        message("[WARN] Will generate new PSA samples")
      }
    } else {
      message("[WARN] PSA samples file is invalid or corrupted")
      message("[WARN] Will generate new PSA samples")
    }
    
  }, error = function(e) {
    message("[WARN] Error loading PSA samples: ", e$message)
    message("[WARN] Will generate new PSA samples")
  })
}

# Generate new PSA samples if not loaded
if (!psa_loaded) {
  message("[INFO] Generating NEW PSA parameter samples...")
  
  psa_samples_output <- generate_psa_samples(params_bc, n_sim = N_SIMULATIONS, seed = RANDOM_SEED)
  psa_parameter_samples <- psa_samples_output$samples
  psa_parameter_df <- psa_samples_output$psa_df
  
  # Save for future use
  message("[INFO] Saving PSA samples for future use...")
  saveRDS(psa_samples_output, psa_samples_file)
  message("[INFO] PSA samples saved to:", psa_samples_file)
  
  message("\n[TIP] To visualize PSA distributions, run: source('run_psa_distributions_only.R')")
}

message("[INFO] PSA parameter samples ready (n = ", length(psa_parameter_samples), ")\n")

# ============================================================
# RUN ANALYSES FOR EACH PERSPECTIVE
# ============================================================

# Store all results
all_results <- list()

for (current_perspective in perspectives_to_run) {
  
  tryCatch({
    
    message("\n========================================")
    message(paste("RUNNING ANALYSIS:", toupper(current_perspective), "PERSPECTIVE"))
    message("========================================\n")
    
   
    
    # UPDATE GLOBAL PERSPECTIVE AND FOLDER STRUCTURE

    # Set perspective
    perspective <- current_perspective
    update_output_folders(current_perspective)
    n_cohort <- as.integer(COHORT_SIZE)
    
    # Create perspective-specific folder for deterministic plots
    if (current_perspective == "healthcare") {
      folder_name <- "Healthcare"
    } else if (current_perspective == "societal") {
      folder_name <- "societal"
    } else {
      folder_name <- current_perspective
    }
    
    OUT_FIG_DETERM <- file.path(OUT_FIG, "DETERMINISTIC", folder_name)
    dir.create(OUT_FIG_DETERM, recursive = TRUE, showWarnings = FALSE)
    message("[INFO] Deterministic plots will be saved to: ", OUT_FIG_DETERM)
    
   
    
    # Reload base parameters with correct perspective
    params_bc <- get_base_params()
    
    # ============================================================
    # DETERMINISTIC ANALYSIS
    # ============================================================
    
    message("[INFO] Running Deterministic Analysis...")
    res_det_list <- eval_all_strategies(params_bc)
    det <- summarize_det(res_det_list, comparator = "MenC")
    
    message("\nDeterministic Results:")
    print(det$table)
    print(det$icers)
    print(det$incremental)
    
    # Plot ICER frontier
    p_icer <- try(plot(det$icers), silent = TRUE)
    if (inherits(p_icer, "ggplot")) {
      filename <- file.path(OUT_FIG_DETERM, paste0("deterministic_icers_frontier_", current_perspective, ".png"))
      try(ggsave(filename, p_icer, width = 7, height = 5, dpi = 300))
      try(print(p_icer))
    }
    
    # ============================================================
    # PSA - REUSE PARAMETER SAMPLES, RECALCULATE OUTCOMES
    # ============================================================
    
    message("\n[INFO] Running PSA with pre-generated parameter samples...")
    message(paste("[INFO] Perspective:", current_perspective))
    
    # Setup parallel cluster
    n_cores <- parallel::detectCores() - 1
    if (is.na(n_cores) || n_cores < 1) n_cores <- 1
    
    cl <- parallel::makeCluster(n_cores)
    doParallel::registerDoParallel(cl)
    
    log_info(paste("Running", N_SIMULATIONS, "PSA simulations on", n_cores, "cores..."))
    
    # Update perspective in each parameter sample
    psa_samples_perspective <- lapply(psa_parameter_samples, function(s) {
      s$perspective <- current_perspective
      return(s)
    })
    
    # Run simulations in parallel with UPDATED parameter sets
    psa_results <- foreach::foreach(
      i = 1:N_SIMULATIONS,
      .combine = 'rbind',
      .packages = c('dplyr', 'tibble', 'darthtools'),
      .export = c(
        # Functions
        "eval_all_strategies", "eval_strategy", "build_transition_array",
        "run_markov", "get_serogroup_ve", "shift_ve", ".clamp",
        "get_state_costs", "get_state_utils", "vaccination_costs",
        # Logging functions
        "log_info", "log_warn", "log_error",
        # Global variables
        "v_strats", "v_states", "n_states", "c_prod_societal",
        "v_discount_cost", "v_discount_qaly", "n_cohort"
      )
    ) %dopar% {
      # Evaluate all strategies for this parameter set
      r_i <- eval_all_strategies(psa_samples_perspective[[i]])
      
      # Return results as tibble
      tibble::tibble(
        sim = i,
        Strategy = names(r_i),
        Cost  = vapply(r_i, function(x) x$cost, numeric(1)),
        QALYs = vapply(r_i, function(x) x$qalys, numeric(1))
      )
    }
    
    # Stop parallel cluster
    parallel::stopCluster(cl)
    
    # Calculate NMB
    psa_results <- psa_results %>%
      dplyr::mutate(NMB = QALYs * WTP_THRESHOLD - Cost)
    
    log_info("PSA completed successfully")
    
    # Create PSA objects
    objs <- make_psa_objects(psa_results, strategies = v_strats, wtp_vec = v_wtp)
    
    # Plot CEAC
    p_ceac <- try(plot(objs$ceac), silent = TRUE)
    if (inherits(p_ceac, "ggplot")) {
      filename <- file.path(OUT_FIG_DETERM, paste0("psa_ceac_", current_perspective, ".png"))
      try(ggsave(filename, p_ceac, width = 7, height = 5, dpi = 300))
    }
    
    # Plot EVPI
    p_evpi <- try(plot(objs$evpi), silent = TRUE)
    if (inherits(p_evpi, "ggplot")) {
      filename <- file.path(OUT_FIG_DETERM, paste0("psa_evpi_", current_perspective, ".png"))
      try(ggsave(filename, p_evpi, width = 7, height = 5, dpi = 300))
    }
    
    # ============================================================
    # OWSA
    # ============================================================
    
    if (CREATE_OWSA_PLOTS) {
      message("\n[INFO] Running One-Way Sensitivity Analysis (OWSA)...")
      message("[INFO] OWSA plots will be saved to: ", OUT_FIG_OWSA)
      
      if (length(owsa_comparators) == 1 && owsa_comparators == "all") {
        owsa_comparators <- v_strats
      }
      
      owsa_out <- execute_owsa(
        params_bc, 
        comparators = owsa_comparators,
        strategies_to_test = owsa_strategies
      )
      
      # Generate tornado plots
      create_owsa_plots(
        owsa_out, 
        det, 
        strategies = owsa_strategies,
        wtp = WTP_THRESHOLD,
        plot_type = "both",
        perspective = current_perspective
      )
      
    } else {
      owsa_out <- NULL
      message("\n[INFO] OWSA plots skipped (CREATE_OWSA_PLOTS = FALSE)")
    }
    
    # ============================================================
    # SAVE RESULTS
    # ============================================================
    
    message("\n[INFO] Saving results...")
    
    # Add perspective suffix to filenames
    suffix <- paste0("_", current_perspective)
    
    # Save deterministic results table
    tryCatch({
      message("[DEBUG] Saving deterministic results table...")
      readr::write_csv(det$table, file.path(OUT_TAB, paste0("deterministic_results", suffix, ".csv")))
      message("[DEBUG] ✓ Deterministic table saved")
    }, error = function(e) {
      message("[ERROR] Failed to save deterministic table: ", e$message)
    })
    
    # Save ICERs
    tryCatch({
      message("[DEBUG] Saving ICERs...")
      icers_df <- as.data.frame(det$icers, stringsAsFactors = FALSE)
      readr::write_csv(icers_df, file.path(OUT_TAB, paste0("deterministic_icers", suffix, ".csv")))
      message("[DEBUG] ✓ ICERs saved")
    }, error = function(e) {
      message("[ERROR] Failed to save ICERs: ", e$message)
      message("[INFO] Trying alternative ICER save method...")
      tryCatch({
        icers_df <- data.frame(
          Strategy = as.character(det$icers$Strategy),
          Cost = as.numeric(det$icers$Cost),
          Effect = as.numeric(det$icers$Effect),
          Inc_Cost = as.numeric(det$icers$Inc_Cost),
          Inc_Effect = as.numeric(det$icers$Inc_Effect),
          ICER = as.numeric(det$icers$ICER),
          Status = as.character(det$icers$Status),
          stringsAsFactors = FALSE
        )
        readr::write_csv(icers_df, file.path(OUT_TAB, paste0("deterministic_icers", suffix, ".csv")))
        message("[DEBUG] ✓ ICERs saved (alternative method)")
      }, error = function(e2) {
        message("[ERROR] Alternative ICER save also failed: ", e2$message)
      })
    })
    
    # Save incremental epidemiological results
    tryCatch({
      message("[DEBUG] Saving incremental epi results...")
      readr::write_csv(det$incremental, file.path(OUT_TAB, paste0("deterministic_incremental_epi", suffix, ".csv")))
      message("[DEBUG] ✓ Incremental epi saved")
    }, error = function(e) {
      message("[ERROR] Failed to save incremental epi: ", e$message)
      message("[DEBUG] Class of det$incremental: ", class(det$incremental))
      message("[DEBUG] Is dataframe?: ", is.data.frame(det$incremental))
    })
    
    # Save PSA results
    tryCatch({
      message("[DEBUG] Saving PSA results...")
      readr::write_csv(psa_results, file.path(OUT_TAB, paste0("psa_long_results", suffix, ".csv")))
      message("[DEBUG] ✓ PSA results saved")
    }, error = function(e) {
      message("[ERROR] Failed to save PSA results: ", e$message)
      message("[DEBUG] Class of psa_results: ", class(psa_results))
      message("[DEBUG] Is dataframe?: ", is.data.frame(psa_results))
    })
    
    # Save OWSA results (handle multiple comparators)
    if (!is.null(owsa_out)) {
      tryCatch({
        message("[DEBUG] Saving OWSA results...")
        # Check if multiple comparators (new format) or single comparator (old format)
        if ("comparator" %in% names(owsa_out)) {
          # Single comparator - old format
          message("[DEBUG] Single comparator format detected: ", owsa_out$comparator)
          readr::write_csv(owsa_out$owsa_Cost, 
                           file.path(OUT_TAB, paste0("owsa_output_cost_", owsa_out$comparator, suffix, ".csv")))
          readr::write_csv(owsa_out$owsa_QALYs, 
                           file.path(OUT_TAB, paste0("owsa_output_qalys_", owsa_out$comparator, suffix, ".csv")))
          message("[DEBUG] ✓ OWSA saved (single comparator)")
        } else {
          # Multiple comparators - new format (loop through each comparator)
          message("[DEBUG] Multiple comparator format detected: ", paste(names(owsa_out), collapse = ", "))
          for (comp in names(owsa_out)) {
            message("[DEBUG] Saving OWSA for comparator: ", comp)
            readr::write_csv(owsa_out[[comp]]$owsa_Cost, 
                             file.path(OUT_TAB, paste0("owsa_output_cost_", comp, suffix, ".csv")))
            readr::write_csv(owsa_out[[comp]]$owsa_QALYs, 
                             file.path(OUT_TAB, paste0("owsa_output_qalys_", comp, suffix, ".csv")))
          }
          message("[DEBUG] ✓ OWSA saved (multiple comparators)")
        }
      }, error = function(e) {
        message("[ERROR] Failed to save OWSA: ", e$message)
      })
    }
    
    # Store results
    all_results[[current_perspective]] <- list(
      deterministic = det,
      psa = psa_results,
      psa_objects = objs,
      owsa = owsa_out
    )
    
    message(paste("\n[INFO] ===", toupper(current_perspective), "perspective analysis completed successfully ===\n"))
  }, error = function(e) {
    message("\n========================================")
    message(paste("ERROR:", toupper(current_perspective), "PERSPECTIVE FAILED"))
    message("========================================")
    message(paste("Error message:", e$message))
    message("\nStacktrace:")
    traceback()
    message("========================================\n")
  })
}

# ============================================================
# PRINT SUMMARY FOR ALL PERSPECTIVES
# ============================================================

message("\n========================================")
message("ANALYSIS SUMMARY - ALL PERSPECTIVES")
message("========================================")

for (persp in perspectives_to_run) {
  if (!is.null(all_results[[persp]])) {
    message("\n", strrep("=", 50))
    message(paste("PERSPECTIVE:", toupper(persp)))
    message(strrep("=", 50))
    
    # Deterministic results
    message("\n--- DETERMINISTIC RESULTS ---")
    print(all_results[[persp]]$deterministic$table)
    
    message("\n--- ICERS ---")
    print(all_results[[persp]]$deterministic$icers)
    
    # PSA summary
    if (!is.null(all_results[[persp]]$psa)) {
      message("\n--- PSA SUMMARY ---")
      psa_summary_by_strat <- all_results[[persp]]$psa %>%
        dplyr::group_by(Strategy) %>%
        dplyr::summarise(
          Mean_Cost = mean(Cost),
          SD_Cost = sd(Cost),
          Mean_QALYs = mean(QALYs),
          SD_QALYs = sd(QALYs),
          Mean_NMB = mean(NMB),
          SD_NMB = sd(NMB),
          .groups = "drop"
        )
      print(psa_summary_by_strat)
    }
  }
}

message("\n[INFO] Script completed successfully!\n")

# ============================================================
# CALCULATE & DISPLAY TOTAL TIME
# ============================================================
end_time <- Sys.time()
total_time <- end_time - start_time
message(paste("\n[INFO] Total execution time:", round(total_time, 2)))
# ============================================================

message("\n========================================")
message("ALL ANALYSES COMPLETE")
message("========================================")
message(paste("Results saved to:", OUT_TAB))
message(paste("Figures saved to:", OUT_FIG))
message(paste("Perspectives analyzed:", paste(perspectives_to_run, collapse = ", ")))
message("========================================\n")

# ============================================================
# CLEANUP
# ============================================================

# Optional: Clean up large objects to free memory
# Uncomment if needed
# rm(all_results, psa_parameter_samples)
# gc()

message("\n[INFO] Script completed. Check outputs folder for results.\n")